#' Resample likelihood rasters to common resolution/extent
#' 
#' @param L.rasters list of individual likelihood rasters generated by calc
#'   functions
#' @param res raster or raster brick indicating desired output resolution
#'   of all likelihood rasters. 
#'   
#' @return a list of all resampled likelihood rasters and g, the common grid
#' @export
#' @references Pedersen MW, Patterson TA, Thygesen UH, Madsen H (2011)
#'   Estimating animal behavior and residency from movement data. Oikos
#'   120:1281-1290. doi: 10.1111/j.1600-0706.2011.19044.x
#'   
#' @examples
#' none
#' 
resample.grid <- function(L.rasters, res){
  
  for (i in 1:length(L.rasters)){
    r <- L.rasters[[i]]
    t <- Sys.time()
    r <- raster::resample(r, res)
    print(Sys.time() - t)
    L.rasters[[i]] <- r
  }
  
  g <- setup.grid.raster(res)
  
  list(L.rasters, g)
  
}
