#' Resample likelihood rasters to common resolution/extent
#' 
#' @param L.rasters list of individual likelihood rasters generated by calc
#'   functions
#' @param res raster or raster brick indicating desired output resolution
#'   of all likelihood rasters. 
#'   
#' @return a list of all resampled likelihood rasters and g, the common grid
#' @export
#' @examples
#' none
#' 
resample.grid <- function(L.rasters, L.res){
  
  start.t <- Sys.time()
  
  L.rasters.old <- L.rasters
  
  for (i in 1:length(L.rasters)){
    r <- L.rasters[[i]]
    
    if (i == 1){
      resol <- raster::res(r)[1]
    } else{
      resol <- c(resol, raster::res(r)[1])
    }
    
    t <- Sys.time()
    r <- raster::resample(r, L.res)
    print(Sys.time() - t)
    r[r == 0] <- NA
    L.rasters[[i]] <- r

  }
  
  print(resol)
  
  L.mle.res <- L.rasters.old[which(resol == max(resol))][[1]]
  
  g <- setup.grid.raster(L.res)
  g.mle <- setup.grid.raster(L.mle.res)
  
  print(paste('Raster resample took ', Sys.time() - start.t, '.'))
  
  list(L.rasters, L.mle.res = L.mle.res, g = g, g.mle = g.mle)
  
}
